### ISSUE TITLE
POST /v1/admin/register 注册管理员失败

### ISSUE THREAD

**Issue by Gotoff** [liangfengbo/nodejs-koa-blog#20]
POST : http://localhost:3000/v1/admin/register?nickname=klimt&password1=12345_abAB&password2=12345_abAB&email=klimtphoto@126.com
返回消息如下：
"msg": [
        "WHERE parameter \"email\" has invalid \"undefined\" value"
    ],
    "error_code": 10000,
    "request": "POST /v1/admin/register"

从代码来看，LinValidator._check这个函数在走到isCustomFunc分支时，this.data还是未定义的无效值，并没有更新为传入的email值，所以会报异常。

**Comment by liangfengbo** [comment]
> POST : [http://localhost:3000/v1/admin/register?nickname=�klimt&password1=12345_abAB&password2=12345_abAB&email=klimtphoto@126.com](http://localhost:3000/v1/admin/register?nickname=%08klimt&password1=12345_abAB&password2=12345_abAB&email=klimtphoto@126.com)
> 返回消息如下：
> "msg": [
> "WHERE parameter "email" has invalid "undefined" value"
> ],
> "error_code": 10000,
> "request": "POST /v1/admin/register"
> 
> 从代码来看，LinValidator._check这个函数在走到isCustomFunc分支时，this.data还是未定义的无效值，并没有更新为传入的email值，所以会报异常。

首先你需要确定是POST方式，第二你要确定是body传值

**Comment by Gotoff** [comment]
确实是我传入参数有错误，没有在body里面，多谢答复哈🌹
