### ISSUE TITLE
page small small bug

### ISSUE THREAD

**Issue by xiaotiandada** [liangfengbo/nodejs-koa-blog#28]
![image](https://user-images.githubusercontent.com/24250627/63911145-e12a6f00-ca5b-11e9-8ede-58506a78417d.png)

如果不能确保内容充实填满, 还是做一下处理比较好

**Comment by liangfengbo** [comment]
> ![image](https://user-images.githubusercontent.com/24250627/63911145-e12a6f00-ca5b-11e9-8ede-58506a78417d.png)
> 
> 如果不能确保内容充实填满, 还是做一下处理比较好

好的，谢谢你的建议，我不断优化完善此项目的。前端的样式你也可以修改成你喜欢的哦~
