### ISSUE TITLE
可能是我自己的问题，因为新学这些东西可能有地方完全不明白。

### ISSUE THREAD

**Issue by jason1118** [liangfengbo/nodejs-koa-blog#31]
可能是我自己的问题，因为新学这些东西可能有地方完全不明白。
我现在可以打开8080和8083，3000这个注册页面找不到~~~
数据库没啥问题~~
![SX@JV5IUYV3_P{_@W$MS%7F](https://user-images.githubusercontent.com/44317940/63218666-f1a43500-c191-11e9-8f2c-2a4e0861ccc4.png)

_Originally posted by @tenderzada in https://github.com/liangfengbo/nodejs-koa-blog/issues/26#issuecomment-522280325_

这个没有问题，因为'/'没有绑定任何东西，所以是404，只要借口可以访问就没问题，输出的是sequelize调试的信息，如果项关闭，需要在db.js中给logging设置为false。祝你顺利！

**Comment by liangfengbo** [comment]
> 可能是我自己的问题，因为新学这些东西可能有地方完全不明白。
> 我现在可以打开8080和8083，3000这个注册页面找不到~~~
> 数据库没啥问题~~
> ![SX@JV5IUYV3_P{_@W$MS%7F](https://user-images.githubusercontent.com/44317940/63218666-f1a43500-c191-11e9-8f2c-2a4e0861ccc4.png)
> 
> _Originally posted by @tenderzada in [#26 (comment)](https://github.com/liangfengbo/nodejs-koa-blog/issues/26#issuecomment-522280325)_
> 
> 这个没有问题，因为'/'没有绑定任何东西，所以是404，只要借口可以访问就没问题，输出的是sequelize调试的信息，如果项关闭，需要在db.js中给logging设置为false。祝你顺利！

你好，非常抱歉，你提问后就直接close了，请问你在目录下运行koa项目了吗？现在解决问题了吗？如果还有问题请留言，我会及时回复的，共勉，谢谢！
