### ISSUE TITLE
'nodemon' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒ ▒▒▒▒▒▒▒▒▒ļ▒▒▒ npm ERR! code ELIFECYCLE npm ERR! errno 1

### ISSUE THREAD

**Issue by ying2025** [liangfengbo/nodejs-koa-blog#50]
0 info it worked if it ends with ok
1 verbose cli [ 'F:\\nodejs\\node.exe',
1 verbose cli   'F:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle nodejs-koa2-blog@1.0.0~predev: nodejs-koa2-blog@1.0.0
6 info lifecycle nodejs-koa2-blog@1.0.0~dev: nodejs-koa2-blog@1.0.0
7 verbose lifecycle nodejs-koa2-blog@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle nodejs-koa2-blog@1.0.0~dev: PATH: F:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\jsSpace\rent-house\nodejs-koa-blog\node_modules\.bin;C:\Users\zhr\bin;F:\Git\mingw64\bin;F:\Git\usr\local\bin;F:\Git\usr\bin;F:\Git\usr\bin;F:\Git\mingw64\bin;F:\Git\usr\bin;C:\Users\zhr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;F:\JAVA\jdk1.8.0\bin;F:\JAVA\jdk1.8.0\jre\bin;%CATALINA_HOME%\bin;%CATALINA_HOME%\lib;F:\JAVA\apache-maven\bin;F:\nodejs;F:\Git\cmd;F:\Go\bin;F:\Geth;F:\Python27;F:\MATLAB\R2019a\bin;F:\TDM-GCC-64\bin;F:\Python27;C:\Users\zhr\AppData\Local\Microsoft\WindowsApps;C:\Users\zhr\AppData\Local\atom\bin;C:\Users\zhr\AppData\Roaming\npm;C:\Users\zhr\go\bin;F:\JetBrains\CLion 2018.3.3\bin;F:\Git\usr\bin\vendor_perl;F:\Git\usr\bin\core_perl
9 verbose lifecycle nodejs-koa2-blog@1.0.0~dev: CWD: D:\jsSpace\rent-house\nodejs-koa-blog
10 silly lifecycle nodejs-koa2-blog@1.0.0~dev: Args: [ '/d /s /c', 'nodemon app.js' ]
11 silly lifecycle nodejs-koa2-blog@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle nodejs-koa2-blog@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: nodejs-koa2-blog@1.0.0 dev: `nodemon app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (F:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (F:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid nodejs-koa2-blog@1.0.0
15 verbose cwd D:\jsSpace\rent-house\nodejs-koa-blog
16 verbose Windows_NT 10.0.14393
17 verbose argv "F:\\nodejs\\node.exe" "F:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error nodejs-koa2-blog@1.0.0 dev: `nodemon app.js`
22 error Exit status 1
23 error Failed at the nodejs-koa2-blog@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by liangfengbo** [comment]
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'F:\nodejs\node.exe',
> 1 verbose cli 'F:\nodejs\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli 'run',
> 1 verbose cli 'dev' ]
> 2 info using npm@6.4.1
> 3 info using node@v8.12.0
> 4 verbose run-script [ 'predev', 'dev', 'postdev' ]
> 5 info lifecycle nodejs-koa2-blog@1.0.0~predev: nodejs-koa2-blog@1.0.0 6 info lifecycle nodejs-koa2-blog@1.0.0~dev: nodejs-koa2-blog@1.0.0
> 7 verbose lifecycle nodejs-koa2-blog@1.0.0~dev: unsafe-perm in lifecycle true 8 verbose lifecycle nodejs-koa2-blog@1.0.0~dev: PATH: F:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\jsSpace\rent-house\nodejs-koa-blog\node_modules.bin;C:\Users\zhr\bin;F:\Git\mingw64\bin;F:\Git\usr\local\bin;F:\Git\usr\bin;F:\Git\usr\bin;F:\Git\mingw64\bin;F:\Git\usr\bin;C:\Users\zhr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;F:\JAVA\jdk1.8.0\bin;F:\JAVA\jdk1.8.0\jre\bin;%CATALINA_HOME%\bin;%CATALINA_HOME%\lib;F:\JAVA\apache-maven\bin;F:\nodejs;F:\Git\cmd;F:\Go\bin;F:\Geth;F:\Python27;F:\MATLAB\R2019a\bin;F:\TDM-GCC-64\bin;F:\Python27;C:\Users\zhr\AppData\Local\Microsoft\WindowsApps;C:\Users\zhr\AppData\Local\atom\bin;C:\Users\zhr\AppData\Roaming\npm;C:\Users\zhr\go\bin;F:\JetBrains\CLion 2018.3.3\bin;F:\Git\usr\bin\vendor_perl;F:\Git\usr\bin\core_perl
> 9 verbose lifecycle nodejs-koa2-blog@1.0.0~dev: CWD: D:\jsSpace\rent-house\nodejs-koa-blog 10 silly lifecycle nodejs-koa2-blog@1.0.0~dev: Args: [ '/d /s /c', 'nodemon app.js' ]
> 11 silly lifecycle nodejs-koa2-blog@1.0.0~dev: Returned: code: 1 signal: null 12 info lifecycle nodejs-koa2-blog@1.0.0~dev: Failed to exec dev script
> 13 verbose stack Error: nodejs-koa2-blog@1.0.0 dev: `nodemon app.js`
> 13 verbose stack Exit status 1
> 13 verbose stack at EventEmitter. (F:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
> 13 verbose stack at emitTwo (events.js:126:13)
> 13 verbose stack at EventEmitter.emit (events.js:214:7)
> 13 verbose stack at ChildProcess. (F:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack at emitTwo (events.js:126:13)
> 13 verbose stack at ChildProcess.emit (events.js:214:7)
> 13 verbose stack at maybeClose (internal/child_process.js:915:16)
> 13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid nodejs-koa2-blog@1.0.0
> 15 verbose cwd D:\jsSpace\rent-house\nodejs-koa-blog
> 16 verbose Windows_NT 10.0.14393
> 17 verbose argv "F:\nodejs\node.exe" "F:\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev"
> 18 verbose node v8.12.0
> 19 verbose npm v6.4.1
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error nodejs-koa2-blog@1.0.0 dev: `nodemon app.js`
> 22 error Exit status 1
> 23 error Failed at the nodejs-koa2-blog@1.0.0 dev script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

什么?
