### ISSUE TITLE
后续能扩展为多人博客吗

### ISSUE THREAD

**Issue by debuggor** [liangfengbo/nodejs-koa-blog#51]
大佬，后续能扩展为多人博客吗
很喜欢这个风格，和掘金主题很像

**Comment by liangfengbo** [comment]
> 大佬，后续能扩展为多人博客吗
> 很喜欢这个风格，和掘金主题很像

谢谢你哦，这个开源项目的目的是为了帮助更多朋友们学习、参考，后续功能会越来越完善的。欢迎一起学习完善这个项目。
