### ISSUE TITLE
老师，请问管理员登录页面的逻辑是怎么绑定的？

### ISSUE THREAD

**Issue by hs-huang** [liangfengbo/nodejs-koa-blog#64]
<body style="height: 100%;">
	登录测试
<div id="app" style="height: 100%;"></div>

</body>
</html>

源代码中首页index.html文件中的<body>只有一个div，请问是如何加载到那么多的部件的（例如登录表单、背景）？

**Comment by hs-huang** [comment]
我是的目的想模仿登录页面，写一个管理员注册页面

**Comment by liangfengbo** [comment]
> 登录测试
> 源代码中首页index.html文件中的只有一个div，请问是如何加载到那么多的部件的（例如登录表单、背景）？

你好，你有学过 Vue.js 吗？后台管理系统是用 Vue 写的哦

**Comment by liangfengbo** [comment]
> > 登录测试
> > 源代码中首页index.html文件中的只有一个div，请问是如何加载到那么多的部件的（例如登录表单、背景）？
> 
> 你好，你有学过 Vue.js 吗？后台管理系统是用 Vue 写的哦
